### ISSUE TITLE
How do I enable gzip for everything?

### ISSUE THREAD

**Issue by sunshineo** [willrstern/nginx-etcd#1]
We have gzip on but that only works for html by default. Need to have the gzip type line uncommented https://github.com/willrstern/nginx-etcd/blob/master/nginx.conf#L49

So do we have to fork the repo, modify the file and build our own image?

**Comment by willrstern** [comment]
Got it added with: https://github.com/willrstern/nginx-etcd/pull/2
The image with that fix is pushed, too!

**Comment by sunshineo** [comment]
Can we add application/javascript to that line?
Is it the right thing to do to simply uncomment that line? Should this be part of some configuration?

**Comment by learncodeacademy** [comment]
`gzip_types` is configured by default, it's just `text/html`, so uncommenting that line is fine with me.  I don't see it causing anyone issues.  I can add `application/javascript` as well.

Another thing you can do if you want more customized configuration is build from my base image and add your own `nginx.conf`

``` Dockerfile
FROM willrstern/nginx-etcd

COPY ./nginx.conf /etc/nginx/nginx.conf
```

**Comment by sunshineo** [comment]
@learncodeacademy  Thank you for your help. I think customized build is the right way to handle this.

**Comment by willrstern** [comment]
@sunshineo eventually, I added #3 since doing it without building a new container would be nice.
